---
name: java-assignment-solution-100-01
break: true
indent: 4
revision: feature/use-linters-plugins
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labone/DisplayOutput.java:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 2
            CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
            # --fragment "println(" --count 4 --exact
            # --fragment "new Date(" --count 1 --exact

# --> check the technical writing
# mdl is a Markdown linting tool
writing/reflection.md:
    mdl
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    # --paragraphs 1 --exact
    # --words 200

# --> check the number of commits beyond a threshold
CountCommits --count 10

# --> check that the program executes correctly and produces 4 lines of output
ExecuteCommand --command "gradle -q --console plain run"
CountCommandOutput --command "gradle -q --console plain run" --count 4 --exact
