---
name: java-assignment-solution-100-01
break: true
indent: 4
revision: feature/use-linters-plugins
---

# Reminders:
# --> a check without an "--exact" the check is an "at least"
# --> checks below a file in a directory are for that specific content
# --> checks that appear stand-alone are for an entire repository

# --> check the source code for various characteristics
src/main:
    java:
        labone/DisplayOutput.java:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 2
            CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "new Date()" --count 1 --exact
            MatchFileRegex --regex "println\((.)*\)" --count 1 --exact

# --> check the technical writing
# mdl is a Markdown linting tool
writing/reflection.md:
    mdl
    ConfirmFileExists
    CountFileWords --count 300
    CountMarkdownTags --tag "heading" --count 6 --exact
    CountMarkdownTags --tag "code" --count 3 --exact
    CountMarkdownTags --tag "code_block" --count 1 --exact
    CountMarkdownTags --tag "list" --count 1 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact

# --> check that the number of commits is beyond a threshold
CountCommits --count 10

# --> check that the program executes correctly and produces exactly 4 lines of output
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle -q --console plain run"
CountCommandOutput --command "gradle -q --console plain run" --count 4 --exact
